# Generated by Django 3.0.3 on 2020-07-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='published_at',
        ),
    ]
