# Generated by Django 3.0.3 on 2020-07-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20200708_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('cv', models.FileField(upload_to='apply/')),
                ('coverletter', models.TextField(max_length=500)),
            ],
        ),
    ]
