# Generated by Django 3.0.3 on 2020-07-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
