# Generated by Django 3.0.3 on 2020-07-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_auto_20200710_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
