# Generated by Django 3.0.3 on 2020-07-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_auto_20200710_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
